### ISSUE TITLE
TikTok Captcha

### ISSUE THREAD

**Issue by spherebread** [captaincolonelfox/TeleTok#18]
![image](https://user-images.githubusercontent.com/48400794/147663212-0d24f6b9-a6ad-4068-883e-4313780377b8.png)
Seems like we are doomed 🤔

Direct links (like this https://vm.tiktok.com/ZSeukVFjv/) initiate captcha sometimes.
https://m.tiktok.com/v/7022940447685364994.html

**Comment by captaincolonelfox** [comment]
Hi!

Thanks for informing me about the captcha, very appricaite it

Though as I can see on a Sentry log, I'm not getting a captcha, but they have changed the page content.
However I still can get a video URL, so I will do a fix and draft a new release soon

![image](https://user-images.githubusercontent.com/23484721/147690609-82b93902-136e-4aff-8a88-30fe80baa0b4.png)



In case of captcha, we can try to use a logged in user session (with solved captcha) or maybe to pretend to be a mobile app (they are not showing a captcha on mobile app, arent they).
In worst case we can use a [phantomjs](https://github.com/ariya/phantomjs) or [requests-html](https://github.com/kennethreitz/requests-html) libs to render a javascript page and solve the captha automatically

I will try to spend some time investigating the captcha issue

**Comment by captaincolonelfox** [comment]
@SphereBread
Seems like updating the way I was parsing the page is hepled to fix the recent issue with the bot
And there was no captcha for me, so I I'm not sure if it will cause problems for us in the future 

I will leave this issue open for some time until I'm get sure that bot is working fine 

You can pull the latest [Release 2.2.0](https://github.com/captaincolonelfox/TeleTok/releases)
