### ISSUE TITLE
Не работает на VPS и Heroku

### ISSUE THREAD

**Issue by RERCON0** [captaincolonelfox/TeleTok#21]
Привет. Попробовал установить на VPS, бот отправил одно видео и отключился, ругается на таймаут. Пробовал прописывать user_agent, также ничего не изменилось. Попробовал на Heroku поставить, ноль реакции. За день до этого сдох другой бот для тиктока (также с гитхаба), также перестал присылать видео и в принципе отвечать. Делает это с очень большими задержками. Пинг до api.telegram.org большой. Либо я с кривыми руками, либо что-то где-то сломалось. Стоит отдельный бот для ютуба, он всё исправно присылает. 
![image](https://user-images.githubusercontent.com/100621006/156898337-664666a2-8928-4a89-92ef-f56bbc88b8b9.png)

**Comment by RERCON0** [comment]
Нашел решение проблемы, возможно, временное. Создал бота на другом аккаунте и всё нормально заработало. Видимо проблема была в предыдущем боте, который ежесекундно обращался к api.telegram.org, из-за чего телеграм ограничил подключение бота. В прочем остается неясным, почему тогда другие боты исправно работают?

**Comment by captaincolonelfox** [comment]
Привет.

Насколько я вижу из логов со скриншота, бот подключается к АПИ телеграмма - проблема точно не в телеграмме или тебе.
Если бот отправляет только одно видео, то очень похоже на то, что тикток определяет бота и в следующих запросах таймаутит его по IP или какому-то фингерпринту, например по `tt_webid_v2`

Задержки могут возникать из-за повторов загрузки - почему-то иногда тикток возвращает видео из рекомендаций, вместо нужного по ссылке. В этом случае бот пытается 3 раза скачать его с небольшим перерывом.

Ты используешь последнюю версию кода? В ней я сделал случайный USER_AGENT, чтобы тиктоку сложнее было определить бота.

И я только что сделал обновление, чтобы куки `tt_webid_v2` менялся между запросами (раньше он менялся только при перезапуске бота) - попробуй загрузить новый код и запустить бота из ветки `dev`

**Comment by RERCON0** [comment]
Ставил последнюю на данный момент версию 3.1. Сейчас попробую поставить новую версию.

**Comment by RERCON0** [comment]
Сейчас попробовал старого бота включить и теперь он вообще ошибку 401 выдает. То есть именно к api не подключается. До этого там большой пинг был.
![image](https://user-images.githubusercontent.com/100621006/156899916-86a2c70b-391c-45b5-a397-f8f4bc58a07e.png)

**Comment by captaincolonelfox** [comment]
[Ошибка 401](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/401) значит, что бот не смог авторизоваться - неверный токен, ошибка не в АПИ телеграмма.

Дай мне знать, если изменение с `tt_webid_v2` помогло исправить ошибку с тикток ботом

**Comment by RERCON0** [comment]
Да, забыл токен сменить. Вот, здесь видно, что пинг огромен (это старый бот). Сейчас включу твой, пусть повесит, может заработает.
![image](https://user-images.githubusercontent.com/100621006/156900322-d45fd148-aa42-497c-a29d-c5f3b338831b.png)

**Comment by RERCON0** [comment]
Видео прилетело. Проблема все же на моей стороне
