### ISSUE TITLE
Lack of user filtering

### ISSUE THREAD

**Issue by ViTokarev** [captaincolonelfox/TeleTok#22]
Can you please add a setting: "Only process messages from specific user by User_ID"?

I use the bot exclusively for myself and do not let other users waste my traffic and power on processing their requests.

P.S. it would be cool after adding this function, add such a parameter to run the docker image

**Comment by captaincolonelfox** [comment]
Hi @ViTokarev 
I did an update [v3.2.0](https://github.com/captaincolonelfox/TeleTok/releases/tag/v3.2.0). Now you can run your docker container with another `-e` flag:
`$ docker run -e "API_TOKEN=foo:bar" -e "USER_ID=56789" teletok`
