### ISSUE TITLE
Option for him to respond in channels and respond to bots in a group or channel

### ISSUE THREAD

**Issue by PeraltaEspectru** [captaincolonelfox/TeleTok#23]
I have an RSS FEED feed bot that sends me links to tiktok videos.  But it doesn't respond to messages from another bot, so I always have to manually forward the link for it to download, and I also wanted the option for it to work in channels because it would be great if it had that option.
 One more thing, could he send the video link and the title in the video caption?.

 I know it's asking a lot and I know how difficult it is to make these changes.  Thank you very much in advance.
 And thank you very much for the bot it helped me a lot, it was the best I found on github

**Comment by captaincolonelfox** [comment]
Hi! Glad that you enjoyed it

Yep, I can implement those changes, but can you clarify what exactly do you mean by video title? Is that a tiktok description?
Do you need all those tags, or I can omit them and only grab the text?

**Comment by PeraltaEspectru** [comment]
I think that because of the translation it changed a little of what I wrote.
 1 - It's like this, I wanted him to download a video when he's on a channel too, when I send him a link to a video he doesn't respond.
 2 - When he is in a group he does not download the videos that another bot sends the link.
 3 - about it send a caption with the url of the downloaded video along with the description placed by the author of the tiktok post.  I sent a picture of how it would look more or less.

**Comment by PeraltaEspectru** [comment]
![Screenshot](https://user-images.githubusercontent.com/116016675/207267118-2e2b5fbb-b462-4ef0-925d-abdb94c6b5ac.jpg)

**Comment by captaincolonelfox** [comment]
@PeraltaEspectru Hi, I did an update. You can check if it works for you
The bot should now properly work in channels. And he will add url and video description to his messages

**Comment by PeraltaEspectru** [comment]
I did the test here, it's working perfectly.
Thank you very much...
You helped me a lot with this update, thanks again.

________________________________
De: captaincolonelfox ***@***.***>
Enviado: quarta-feira, 14 de dezembro de 2022 18:36
Para: captaincolonelfox/TeleTok ***@***.***>
Cc: Peralta Espectru ***@***.***>; Mention ***@***.***>
Assunto: Re: [captaincolonelfox/TeleTok] Option for him to respond in channels and respond to bots in a group or channel (Issue #23)


@PeraltaEspectru<https://github.com/PeraltaEspectru> Hi, I did an update. You can check if it works for you
The bot should now properly work in channels. And he will add url and video description to his messages
