### ISSUE TITLE
vid always empty in TikTokAPI.download_video

### ISSUE THREAD

**Issue by jussihi** [captaincolonelfox/TeleTok#24]
Hello, some update to tiktok page code has broken the downloader.

I guess you are aware of that already though :-)

The problematic line is line 51 in api/tiktok.py:
https://github.com/captaincolonelfox/TeleTok/blob/a3aacb6a1a95d2ff18459a4bdf9ba97d15252920/bot/api/tiktok.py#L51

where `vid` is empty for some reason and the downloader cannot download the media.

**Comment by captaincolonelfox** [comment]
Hi @jussihi 

Thank you for your report! I wasn't aware of that :(

I did a fix for that, you can pull the latest code from `main` branch

**Comment by jussihi** [comment]
Hello @captaincolonelfox 

Sorry for not responding, I have merged the updated code to my telegram bot, it works like a charm! Thanks for quick update. Much appreciated!
