### ISSUE TITLE
the bot does not download the images

### ISSUE THREAD

**Issue by PeraltaEspectre** [captaincolonelfox/TeleTok#25]
tiktok updated and has an image download type and it is not downloading

example
bot that can download and a link that downloads images

https://t.me/downloader_tiktok_bot

link tiktok
https://www.tiktok.com/@nicolymodolo__/video/7238763018899770630

test the one I sent you to see how it works and if you have a way to implement it in your code I would be grateful

**Comment by captaincolonelfox** [comment]
Hi!

I will try to take a look at it, but I don’t have enough spare time right now to implement it. I’ll leave this issue open, and maybe someone can do pull request, or eventually I will fix it

**Comment by captaincolonelfox** [comment]
@PeraltaEspectre 
Hi, I did an update, so now you can download photo mode tiktoks similarly as bot you sent doing it

I need some time to deploy it to my [@TeleTokerBot](https://t.me/TeleTockerBot) server, but if you are self hosting, you can already use it

**Comment by PeraltaEspectre** [comment]
Thank you, I'll do the deployment to test.


Thanks so much for taking the time to make the change.

Em sex., 23 de jun. de 2023 22:28, captaincolonelfox <
***@***.***> escreveu:
