### ISSUE TITLE
Bot stops to send a video

### ISSUE THREAD

**Issue by lHolyDiverl** [captaincolonelfox/TeleTok#26]
For a while my copy of the bot was working flawlessly.
About 2 weeks ago the bot stops repsponding and sending video back.
I tried to made a repo fork again but it doesn't helped.

**Comment by captaincolonelfox** [comment]
Hi!

Unfortunately, I don't use my own bot very often, so I wasn't aware of it

So thanks for letting me know about the problem

I've pushed new commits with the fix. You can fetch them to your fork, it should work now

**Comment by lHolyDiverl** [comment]
Me either but I have several people who use it or TikTok :)
I redeploy latest changes and all works fine.
Thank you for your quick update!
Happy New Year!
